-- ODEV6
--1)
-- select SUM(rental_rate) as ortalama from film;
--2)
-- select count(title) from film
-- where title like 'C%'
--3)
-- select max(length) from film
-- where rental_rate=0.99
--4)
-- select count(distinct replacement_cost) from film
-- where length > 150 
